#! /bin/sh
r='/cygdrive/e/mono2'
MONO_CFG_DIR='E:\mono2\runtime\etc'
MONO_SHARED_DIR=$r/runtime
export MONO_CFG_DIR MONO_SHARED_DIR
exec "$r/libtool" --mode=execute -dlopen "$r/mono/mini/libmono-2.0.la" "$r/mono/dis/monodis" "$@"
